#!/usr/bin/env bash
. $(dirname $0)/init_create_crmsh.ini
[ -z $DISK_TYPE ] && {
	echo DISK_TYPE 参数为空;exit 1
	}
[ -z $DISK_NUM ] && {
	echo DISK_NUM 参数为空 ;exit 1
	}
[ -z $DISK_MOUNT_1 ] && {
	echo DISK_MOUNT_1 参数为空 ;exit 1
	}

[ -z $HA_IP_FZ ] && {
	echo HA_IP_FZ 参数为空 ;exit 1
	}

[ -z $HA_PING_GW ] && {
	echo HA_PING_GW 参数为空 ;exit 1
	}


SENDEMAIL_DIR="/usr/local/eyou/mail/sendEmail-v1.56"
[ -d $SENDEMAIL_DIR ] || {
	echo sendEmail-v1.56目录不存在 退出
	exit 1
	}
[ -x $SENDEMAIL_DIR/eyou_mail ] || {
	echo $SENDEMAIL_DIR/eyou_mail 不存在或没有执行权限
	exit 1
	}


CONFIG_FILE="/usr/local/eyou/mail/etc/em_init_config"
[ -f $CONFIG_FILE ] && . $CONFIG_FILE || exit 123

 > ./crmsh

sysconfig_crm () {
echo '
crm configure rsc_defaults resource-stickiness=100
crm configure op_defaults timeout=240s
crm configure property stonith-enabled=false no-quorum-policy=ignore
'
for i in `seq $DISK_NUM`
do
if [ "$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f1|grep ':'|wc -l)" == "0" ];then
echo "
crm configure primitive eyou_mount_disk_${i} ocf:heartbeat:Filesystem params device=$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f1) directory=$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f2) fstype=$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f3) op start interval=0 timeout=60 op stop interval=0 timeout=60 meta migration-threshold=5 resource-stickiness=10
"
else
echo "
crm configure primitive eyou_mount_disk_${i} ocf:heartbeat:Filesystem params device=$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f1) directory=$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f2) fstype=$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f3) options=nolock,tcp op start interval=0 timeout=60 op stop interval=0 timeout=60 meta migration-threshold=5 resource-stickiness=10
crm configure clone eyou_mount_clone_${i} eyou_mount_disk_${i} meta globally-unique=false
"
fi
done
echo '
crm configure primitive eyou_check_disk lsb:eyou_check_disk \
        op monitor interval=5s timeout=15s \
        meta migration-threshold=1 resource-stickiness=10
'
echo "
crm configure primitive eyou_mail_vip ocf:heartbeat:IPaddr2 params ip=$(echo $HA_IP_FZ|cut -d ',' -f1) nic=$(echo $HA_IP_FZ|cut -d ',' -f2) cidr_netmask=$(echo $HA_IP_FZ|cut -d ',' -f3) op monitor interval=30s
crm configure primitive pingd ocf:pacemaker:ping params host_list=$HA_PING_GW multiplier=100 name=pingd op monitor interval=15s timeout=60s
"
}

eyou_crm () {
for i in ${ARRAY_START[@]}
do
	[[ "$i" =~ "cron_etc" ]] && {
	echo "crm configure primitive eyou_$i lsb:eyou_mail_$i op monitor interval=1m timeout=60s"
	} || {
	echo "crm configure primitive eyou_$i lsb:eyou_mail_$i op monitor interval=1m timeout=60s meta migration-threshold=5 resource-stickiness=10 "
	}
done

echo '
crm configure primitive send_email lsb:eyou_check_sendemail \
        op monitor interval="30s" timeout="60s"
'
}

eyou_clo_lo () {
echo '
crm configure primitive eyou_check_network lsb:eyou_check_network \
        op monitor interval=5s timeout=15s
crm configure clone eyou_check_clone eyou_check_network \
        meta globally-unique="false"
'
if [[ "${ARRAY_START[@]} " =~ "filedrepd " ]];then
echo '
crm configure clone eyou_filedrepd_clone eyou_filedrepd \
        meta globally-unique="false"
'
fi
echo '
crm configure clone pingdclone pingd \
        meta globally-unique="false"
crm configure location eyou_check_network_l eyou_check_clone \
        rule -inf: not_defined pingd or pingd lte 0
crm configure location eyou_ping_l eyou_mail_vip \
        rule -inf: not_defined pingd or pingd lte 0
'



if [ "$DISK_NUM" == "1" ] && [ "$DISK_TYPE" == "ext" ];then
echo "#ext =1"
	echo "crm configure colocation eyou_mount_colo inf: eyou_mail_vip eyou_mount_disk_${DISK_NUM} eyou_check_disk"
	echo "crm configure order eyou_mount_after inf: eyou_check_disk eyou_mount_disk_${DISK_NUM} eyou_mail_vip"
elif [ "$DISK_NUM" == "1" ] && [ "$DISK_TYPE" == "nfsext" ];then
echo "#nfsext =1"
	echo "crm configure colocation eyou_mount_colo inf: eyou_mail_vip eyou_mount_disk_${DISK_NUM} eyou_check_disk"
	echo "crm configure order eyou_mount_after inf: eyou_check_disk eyou_mount_disk_${DISK_NUM} eyou_mail_vip"
elif [ "$DISK_NUM" -gt "1" ] && [ "$DISK_TYPE" == "ext" ];then
	echo "#ext gt 1"
		EYOU_MOUNT_DISK=$(for i in `seq $DISK_NUM`;do echo eyou_mount_disk_${i}; done)
		echo "crm configure colocation eyou_disk_colo inf: "${EYOU_MOUNT_DISK}
		echo "crm configure colocation eyou_mount_colo inf: eyou_mail_vip eyou_mount_disk_${DISK_NUM} eyou_check_disk"
		for i in `seq $DISK_NUM`
		do
		echo "crm configure order eyou_mount_after_${i} inf: eyou_check_disk eyou_mount_disk_${i} eyou_mail_vip"
		done
	elif [ "$DISK_NUM" -gt "1" ] && [ "$DISK_TYPE" == "nfsext" ];then
	echo "#nfsext  gt 1"
		EYOU_MOUNT_DISK=$(for i in `seq $DISK_NUM`;do echo eyou_mount_disk_${i}; done)
		echo "crm configure colocation eyou_disk_colo inf: "${EYOU_MOUNT_DISK}
		echo "crm configure colocation eyou_mount_colo inf: eyou_mail_vip eyou_mount_disk_${DISK_NUM} eyou_check_disk"
		for i in `seq $DISK_NUM`
		do
		echo "crm configure order eyou_mount_after_${i} inf: eyou_check_disk eyou_mount_disk_${i} eyou_mail_vip"
		done
	elif [ "$DISK_NUM" == "1" ] && [ "$DISK_TYPE" == "nfs" ];then
	echo "#nfs =1"
		echo "crm configure order eyou_mount_after inf: eyou_mount_clone_${DISK_NUM}  eyou_check_disk eyou_mail_vip"
	elif [ "$DISK_NUM" -gt "1" ] && [ "$DISK_TYPE" == "nfs" ];then
	echo "#nfs gt 1"
		for i in `seq $DISK_NUM`
		do
		echo "crm configure order eyou_mount_after_${i} inf: eyou_mount_clone_${i} eyou_check_disk eyou_mail_vip"
		done
	else
		:

	fi

	echo '
#crm configure order ms_mount_nfs_after inf: eyou_mount_nfs eyou_check_disk eyou_mail_vip
crm configure order eyou_vip_check_after inf: eyou_mail_vip eyou_check_clone
'
if [[ "${ARRAY_START[@]} " =~ "mysql " ]];then
echo '
crm configure colocation eyou_mysql_colo inf: eyou_check_disk eyou_mysql send_email
crm configure order eyou_mysql_after inf: eyou_mail_vip eyou_mysql eyou_mproxy
crm configure order eyou_mysql_sendemail inf: eyou_mysql send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "mysql_index " ]];then
echo '
crm configure colocation eyou_mysql_index_colo inf: eyou_check_disk eyou_mysql_index send_email
crm configure order eyou_mysql_index_after inf: eyou_mail_vip eyou_mysql_index eyou_mproxy_index
crm configure order eyou_mysql_index_sendemail inf: eyou_mysql_index send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "mysql_log " ]];then
echo '
crm configure colocation eyou_mysql_log_colo inf: eyou_check_disk eyou_mysql_log send_email
crm configure order eyou_mysql_log_after inf: eyou_mail_vip eyou_mysql_log
crm configure order eyou_mysql_log_sendemail inf: eyou_mysql_log send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "mproxy " ]];then
echo '
crm configure colocation eyou_mproxy_colo inf: eyou_check_disk eyou_mproxy send_email
crm configure order eyou_mproxy_sendemail inf: eyou_mproxy send_email
crm configure order eyou_mproxy_index_sendemail inf: eyou_mproxy_index send_email
'
fi

if [[ "${ARRAY_START[@]} " =~ "memcache_fix " ]];then
echo '
crm configure colocation eyou_memcache_fix_colo inf: eyou_check_disk eyou_memcache_fix send_email
crm configure order eyou_memcache_fix_after inf: eyou_mysql eyou_memcache_fix
crm configure order eyou_memcache_fix_sendemail inf: eyou_memcache_fix send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "memcache_hot " ]];then
echo '
crm configure colocation eyou_memcache_hot_colo inf: eyou_check_disk eyou_memcache_hot send_email
crm configure order eyou_memcache_hot_after inf: eyou_mysql eyou_memcache_hot
crm configure order eyou_memcache_hot_sendemail inf: eyou_memcache_hot send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "memcache_session " ]];then
echo '
crm configure colocation eyou_memcache_session_colo inf: eyou_check_disk eyou_memcache_session send_email
crm configure order eyou_memcache_session_after inf: eyou_mysql eyou_memcache_session
crm configure order eyou_memcache_session_sendemail inf: eyou_memcache_session send_email
'
fi

if [[ "${ARRAY_START[@]} " =~ "gearman " ]];then
echo '
crm configure colocation eyou_gearman_colo inf: eyou_check_disk eyou_gearman send_email
crm configure order eyou_gearman_after inf: eyou_mysql eyou_gearman
crm configure order eyou_gearman_sendemail inf: eyou_gearman send_email
'
fi

if [[ "${ARRAY_START[@]} " =~ "bounce " ]];then
echo '
crm configure colocation eyou_bounce_colo inf: eyou_check_disk eyou_bounce send_email
crm configure order eyou_bounce_after1 inf: eyou_mproxy eyou_bounce
crm configure order eyou_bounce_after2 inf: eyou_memcache_fix eyou_bounce
crm configure order eyou_bounce_after3 inf: eyou_memcache_session eyou_bounce
crm configure order eyou_bounce_after4 inf: eyou_memcache_hot eyou_bounce
crm configure order eyou_bounce_sendemail inf: eyou_bounce send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "cron_etc " ]];then
echo '
crm configure colocation eyou_cron_etc_colo inf: eyou_check_disk eyou_cron_etc send_email
crm configure order eyou_cron_etc_after inf: eyou_mail_vip eyou_cron_etc
crm configure order eyou_cron_etc_sendemail inf: eyou_cron_etc send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "cleanup " ]];then
echo '
crm configure colocation eyou_cleanup_colo inf: eyou_check_disk eyou_cleanup send_email
crm configure order eyou_cleanup_after inf: eyou_mail_vip eyou_cleanup
crm configure order eyou_cleanup_sendemail inf: eyou_cleanup send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "crtmpd " ]];then
echo '
crm configure colocation eyou_crtmpd_colo inf: eyou_check_disk eyou_crtmpd send_email
crm configure order eyou_crtmpd_after inf: eyou_mail_vip eyou_crtmpd
crm configure order eyou_crtmpd_sendemail inf: eyou_crtmpd send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "filedagent " ]];then
echo '
crm configure order eyou_filedagent_after inf: eyou_mail_vip eyou_filedagent
crm configure order eyou_filedagent_sendemail inf: eyou_filedagent send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "filed " ]];then
echo '
crm configure colocation eyou_filed_colo inf: eyou_check_disk eyou_filed send_email
crm configure order eyou_filed_after inf: eyou_mail_vip eyou_filed
crm configure order eyou_filed_sendemail inf: eyou_filed send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "filedrepd " ]];then
echo '
crm configure order eyou_filedrepd_sendemail inf: eyou_filedrepd_clone send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "httpd " ]];then
echo '
crm configure colocation eyou_httpd_colo inf: eyou_check_disk eyou_httpd send_email
crm configure order eyou_httpd_after inf: eyou_mail_vip eyou_httpd
crm configure order eyou_httpd_sendemail inf: eyou_httpd send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "imap " ]];then
echo '
crm configure colocation eyou_imap_colo inf: eyou_check_disk eyou_imap send_email
crm configure order eyou_imap_after inf: eyou_mproxy eyou_imap
crm configure order eyou_imap_sendemail inf: eyou_imap send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "local " ]];then
echo '
crm configure colocation eyou_local_colo inf: eyou_check_disk eyou_local send_email
crm configure order eyou_local_after1 inf: eyou_mproxy eyou_local
crm configure order eyou_local_after2 inf: eyou_memcache_fix eyou_local
crm configure order eyou_local_after3 inf: eyou_memcache_session eyou_local
crm configure order eyou_local_after4 inf: eyou_memcache_hot eyou_local
crm configure order eyou_local_sendemail inf: eyou_local send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "mlist " ]];then
echo '
crm configure colocation eyou_mlist_colo inf: eyou_check_disk eyou_mlist send_email
crm configure order eyou_mlist_after1 inf: eyou_mproxy eyou_mlist
crm configure order eyou_mlist_after2 inf: eyou_memcache_fix eyou_mlist
crm configure order eyou_mlist_after3 inf: eyou_memcache_session eyou_mlist
crm configure order eyou_mlist_after4 inf: eyou_memcache_hot eyou_mlist
crm configure order eyou_mlist_sendemail inf: eyou_mlist send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "nginx " ]];then
echo '
crm configure colocation eyou_nginx_colo inf: eyou_check_disk eyou_nginx send_email
crm configure order eyou_nginx_after inf: eyou_mail_vip eyou_nginx
crm configure order eyou_nginx_sendemail inf: eyou_nginx send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "phpd " ]];then
echo '
crm configure colocation eyou_phpd_colo inf: eyou_check_disk eyou_phpd send_email
crm configure order eyou_phpd_after1 inf: eyou_mysql_log eyou_phpd
crm configure order eyou_phpd_after2 inf: eyou_gearman eyou_phpd
crm configure order eyou_phpd_sendemail inf: eyou_phpd send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "pop " ]];then
echo '
crm configure colocation eyou_pop_colo inf: eyou_check_disk eyou_pop send_email
crm configure order eyou_pop_after inf: eyou_mproxy eyou_pop
crm configure order eyou_pop_sendemail inf: eyou_pop send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "remote " ]];then
echo '
crm configure colocation eyou_remote_colo inf: eyou_check_disk eyou_remote send_email
crm configure order eyou_remote_after1 inf: eyou_mproxy eyou_remote
crm configure order eyou_remote_after2 inf: eyou_memcache_fix eyou_remote
crm configure order eyou_remote_after3 inf: eyou_memcache_session eyou_remote
crm configure order eyou_remote_after4 inf: eyou_memcache_hot eyou_remote
crm configure order eyou_remote_sendemail inf: eyou_remote send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "smtp " ]];then
echo '
crm configure colocation eyou_smtp_colo inf: eyou_check_disk eyou_smtp send_email
crm configure order eyou_smtp_after inf: eyou_mproxy eyou_smtp
crm configure order eyou_smtp_sendemail inf: eyou_smtp send_email
'
fi
if [[ "${ARRAY_START[@]} " =~ "syslog " ]];then
echo '
crm configure colocation eyou_syslog_colo inf: eyou_check_disk eyou_syslog send_email
crm configure order eyou_syslog_after inf: eyou_mail_vip eyou_syslog
crm configure order eyou_syslog_sendemail inf: eyou_syslog send_email
'
fi

}


sysconfig_crm >>./crmsh
eyou_crm >>./crmsh
eyou_clo_lo >>./crmsh
