#!/usr/bin/env bash
#by liguopeng email:liguopeng@eyou.net
#by zh_CN.UTF8
#[ -f $SENDMAIL_CONF ] && . $SENDMAIL_CONF || exit 1
SENDEMAIL="/usr/local/eyou/mail/sendEmail-v1.56"

#检测crm 是否OK
check_crm () {
if crm status >/dev/null 2>&1;then
	:
else
	[ "$1" != "stop" ] && exit 1 || exit 0
fi
}


#扫描使用ha自动挂载的硬盘
disk_scan () {

#crm configure show xml|grep device |awk '{print $3}'|cut -d '"' -f2 
#crm configure show xml |grep name=\"device\"|awk 'BEGIN { FS="value=" } {print $2}'|cut -d '"' -f2
crm configure show|awk 'BEGIN { FS="device=" } {print $2}'|grep -v '^$'|awk '{print $1","$3}'|cut -d '"' -f4
#DISK_FILE="/data"
#CHECK_FILE="$DISK_FILE/.eyou_check_disk_time"
if [ $? -eq 0 ];then
	exit_val=0
else
	exit_val=1
fi

}

check_disk () {
if [ "$(disk_scan|grep ^nfs$|wc -l)" == "0" ] && [ "$(disk_scan|grep ^ext[1-4]$|wc -l)" != "0" ];then
	$SENDEMAIL/eyou_check_disk_not_nfs $1
	exit $?
elif [ "$(disk_scan|grep ^nfs$|wc -l)" != "0" ] && [ "$(disk_scan|grep ^ext[1-4]$|wc -l)" == "0" ];then
	$SENDEMAIL/eyou_check_disk_nfs $1
	exit $?
elif [ "$(disk_scan|grep ^nfs$|wc -l)" != "0" ] && [ "$(disk_scan|grep ^ext[1-4]$|wc -l)" != "0" ];then
	$SENDEMAIL/eyou_check_disk_not_nfs $1
	exit $?
else
	:
fi

}

case $1 in
	start)
	check_crm
	check_disk start
	exit $?
	;;
	status)
	check_crm
	check_disk status
	exit $?
	;;
	stop)
	check_crm stop
	check_disk stop
	exit $?
	;;
	*)
	echo $"Usage: $0 {start|stop|status}";exit 1
	;;
esac
