#!/usr/bin/env bash
#by liguopeng email:liguopeng@eyou.net
#by zh_CN.UTF8
SENDMAIL_FILE="/usr/local/eyou/mail/sendEmail-v1.56"
pid_name="$(basename $0).pid"
[ -f $SENDMAIL_FILE/check_master_slave ] && . $SENDMAIL_FILE/check_master_slave || exit 1

#检测crm 是否OK
check_crm () {
if crm status >/dev/null 2>&1;then
	:
else
	[ "$1" != "stop" ] && exit 1 || exit 0
fi
}

#获取当前时间戳,并且制定check格式
CHECK_TIME () {
echo "1 $(date +%s)"
}


#扫描使用ha自动挂载的硬盘
disk_scan () {

crm configure show|awk 'BEGIN { FS="device=" } {print $2}'|grep \"ext[1-4]\" |cut -d '"' -f2 && exit_val=0 || exit_val=1
while [ "$exit_val" == "" ];do crm configure show|awk 'BEGIN { FS="device=" } {print $2}'|grep \"ext[1-4]\" |cut -d '"' -f2 && exit_val=0 || exit_val=1 ;done
if [ $exit_val -eq 0 ];then
	exit_val=0
else
	exit_val=1
fi

}

#使用循环扫描 检测磁盘是否挂载
check_disk_mount () {
disk_scan
[ "$(disk_scan)" == "" ] && exit 113
disk_scan_path=$(disk_scan)
if [ "$exit_val" != "0" ];then
	disk_scan_path=$(disk_scan)
	[ "$exit_val" != "0" ] && exit $exit_val
fi

for i in $disk_scan_path
	do
	disk_mount_scan=$(mount -l |awk '{if($1 == "'$i'") {print $3}}'|wc -l)
	if [ $disk_mount_scan -eq 0 ];then
	exit_val=0
	else
	exit_val=1
	fi
done 

}


#启动时候检查动作
start_check () {

[ -f ${EYOU_CHECK_DISK_XT} ] && rm -rf ${EYOU_CHECK_DISK_XT}
[ $(echo -e "${EYOU_DISK_XT}"|grep \/|wc -l) -eq 0 ] && exit 119
fdisk -l ${EYOU_DISK_XT} >/dev/null  2>&1 || exit 133
DISK_TEST_SIZ=$(fdisk -l ${EYOU_DISK_XT} |grep "${EYOU_DISK_XT}"|awk '{print $5}')
if [ "${DISK_TEST_SIZ}" -gt "15697920" ];then echo "$(hostname) $(date +%'F %H:%M:%S') $EYOU_DISK_XT 磁盘大小大于15M...."; exit 123;fi
dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} >/dev/null 2>&1;
until [ -f ${EYOU_CHECK_DISK_XT} ];do dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} >/dev/null 2>&1;done

CHECK_FILE=${EYOU_CHECK_DISK_XT}
check_time_disk_1=$(crm configure show xml |grep eyou_check_disk|grep monitor|awk -F'=' '{print $3}'|cut -d \" -f2|grep -io "[0-9]\{1,3\}"|head -1)
check_time_disk=$(echo "${check_time_disk_1}"+5|bc)

	if [ "$(head -1 $CHECK_FILE|awk '{print $1}')" != "1" ];then CHECK_TIME > $EYOU_CHECK_DISK_XT 2>/dev/null;dd if=${EYOU_CHECK_DISK_XT} of=${EYOU_DISK_XT} >/dev/null 2>&1;echo "$(hostname) $(date +%'F %H:%M:%S') ${EYOU_DISK_XT} 内容非标准 跳过检查 ，将执行mount动作">> $CHECK_DISK_SCAN_CONF; exit_val=0; else exit_val=1;fi
	if [ $exit_val == "1" ];then
		dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} >/dev/null 2>&1
		until [ -f ${EYOU_CHECK_DISK_XT} ];do dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} >/dev/null 2>&1;done
		cat_disk_1=$(head -1 $CHECK_FILE)
		sleep $check_time_disk ;wait
		dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} >/dev/null 2>&1
		until [ -f ${EYOU_CHECK_DISK_XT} ];do dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} >/dev/null 2>&1;done
		cat_disk_2=$(head -1 $CHECK_FILE)
		if [ "$cat_disk_1" == "$cat_disk_2" ];then
			echo "$(hostname) $(date +%'F %H:%M:%S') $EYOU_DISK_XT 磁盘在规定时间内未有改动，将执行mount挂载动作.">>$CHECK_DISK_SCAN_CONF
			CHECK_TIME > $EYOU_CHECK_DISK_XT 2>/dev/null
			dd if=${EYOU_CHECK_DISK_XT} of=${EYOU_DISK_XT} >/dev/null 2>&1
			exit_val=0
		else
			echo "$(hostname) $(date +%'F %H:%M:%S') $EYOU_DISK_XT 磁盘在规定时间内有改动，停止启动,退出.">>$CHECK_DISK_SCAN_CONF
			exit 1;
		fi
	fi
[ $exit_val -eq 0 ] && touch $SENDMAIL_PID_FILE/$pid_name
exit $exit_val
}

#主机服务启动之后 检测状态时更新文件
status_check () {
[ $(echo -e "${EYOU_DISK_XT}"|grep \/|wc -l) -eq 0 ] && exit 119
fdisk -l ${EYOU_DISK_XT} >/dev/null  2>&1 || exit 133
DISK_TEST_SIZ=$(fdisk -l ${EYOU_DISK_XT} |grep "${EYOU_DISK_XT}"|awk '{print $5}')
if [ "${DISK_TEST_SIZ}" -gt "15697920" ];then echo "$(hostname) $(date +%'F %H:%M:%S') $EYOU_DISK_XT 磁盘大小大于15M...."; exit 123;fi
[ -f "$EYOU_CHECK_DISK_XT" ] || exit 113
dd if=${EYOU_DISK_XT} of=/tmp/.test_disk_check >/dev/null 2>&1
until [ -f /tmp/.test_disk_check ];do dd if=${EYOU_DISK_XT} of=/tmp/.test_disk_check >/dev/null 2>&1;done
if [ "$(head -1 /tmp/.test_disk_check|cut -d ' ' -f2)" == "$(head -1 $EYOU_CHECK_DISK_XT|cut -d ' ' -f2)" ];then
	rm -rf /tmp/.test_disk_check
else
	echo "$(hostname) $(date +%'F %H:%M:%S') ${EYOU_DISK_XT} 上一次的磁盘数据非本机修改，退出。">>$CHECK_DISK_SCAN_CONF
	exit 110
fi
CHECK_FILE=${EYOU_CHECK_DISK_XT}
check_time_disk_1=$(crm configure show xml |grep eyou_check_disk|grep monitor|awk -F'=' '{print $3}'|cut -d \" -f2|grep -io "[0-9]\{1,3\}"|head -1)
check_time_disk=$(echo "${check_time_disk_1}"+2|bc)
	CHECK_TIME>$CHECK_FILE 2>/dev/null
	dd if=${EYOU_CHECK_DISK_XT} of=${EYOU_DISK_XT} >/dev/null 2>&1 && exit_val=0 || exit_val=1
if [ $exit_val -eq 0 ];then
	exit $exit_val
else
	echo "$(hostname) $(date +%'F %H:%M:%S') $EYOU_DISK_XT 磁盘数据 写入失败. 等待再次执行结果. 第一次." >>$CHECK_DISK_SCAN_CONF
	if dd if=${EYOU_CHECK_DISK_XT} of=${EYOU_DISK_XT} >/dev/null 2>&1;then exit $? ;else echo "$(hostname) $(date +%'F %H:%M:%S') $EYOU_DISK_XT 磁盘数据写入失败.停止所有服务. 第二次.">>$CHECK_DISK_SCAN_CONF;exit 1;fi
fi
}

stop_check () {
if [ -f $SENDMAIL_PID_FILE/$pid_name ];then
dd if=/dev/zero of=${EYOU_DISK_XT} >/dev/null 2>&1
else
	:
fi
rm -rf ${EYOU_CHECK_DISK_XT}
exit 0
}

case $1 in
	start)
	check_crm
	start_check
	;;
	status)
	[ -f $SENDMAIL_PID_FILE/$pid_name ] || exit 1
	check_crm
	status_check
	;;
	stop)
	[ -f $SENDMAIL_PID_FILE/$pid_name ] || exit 0
	check_crm stop
	rm -rf $SENDMAIL_PID_FILE/$pid_name
	stop_check
	;;
	*)
	echo $"Usage: $0 {start|stop|status}";exit 1
	;;
esac
