#!/usr/bin/env bash
# by liguopeng	email:liguopeng@eyou.net
SENDMAIL_FILE="/usr/local/eyou/mail/sendEmail-v1.56"
EYOU_MAIL="$SENDMAIL_FILE/eyou_mail"

[ -f $SENDMAIL_FILE/check_master_slave ] && . $SENDMAIL_FILE/check_master_slave || exit 121
[ -x $EYOU_MAIL ] && : || exit 122
[ -x $SENDMAIL_FILE/init_eyou_pid ] && $SENDMAIL_FILE/init_eyou_pid || exit 123

DATE_MESS=$(date +'%F %H:%M:%S')

BASE_NAME=$(basename $0)
EYOU_SYS_NAME=$(echo $BASE_NAME|sed 's/eyou_mail_//g')

EYOU_SYS_PIDF=$(echo pidf_${EYOU_SYS_NAME}|tr [a-z] [A-Z])
[ "$EYOU_SYS_PIDF" == "PIDF_CRON_ETC" ] && EYOU_SYS_PIDF="PATH_EM_CROND"
EYOU_SYS_PID_FILE=$(awk -F '=' '{if($1 == "'$EYOU_SYS_PIDF'") {print $2}}' $SENDMAIL_FILE/eyou_mail_pid)

eyou_start () {
#	if $EYOU_MAIL start $EYOU_SYS_NAME >>/dev/null 2>&1;then
	$EYOU_MAIL start $EYOU_SYS_NAME >>/dev/null 2>&1
	exit_val=$?
	while [ "$exit_val" == "" ];do $EYOU_MAIL start $EYOU_SYS_NAME >>/dev/null 2>&1;exit_val=$?;done
	if [ "$exit_val" == "0" ];then
	echo "$DATE_MESS $(hostname) $EYOU_SYS_NAME start [ 启动成功 ] [ OK ]" >>$EYOU_SER_FILE_CONF
	exit_val=0
	else
	echo "$DATE_MESS $(hostname) $EYOU_SYS_NAME start [ 启动失败 ] [ ERROR ]" >>$EYOU_SER_FILE_CONF
	exit_val=1
	fi
	
}

eyou_status () {
#	$EYOU_MAIL watch $EYOU_SYS_NAME >>${EYOU_SER_FILE_CONF}_fail 2>&1
	[ -f $EYOU_SYS_PID_FILE ] || exit 1
#	if $EYOU_MAIL watch $EYOU_SYS_NAME > /dev/null 2>&1;then
#	$EYOU_MAIL watch $EYOU_SYS_NAME > /dev/null 2>&1
	$EYOU_MAIL watch $EYOU_SYS_NAME 1 > /dev/null 2>>${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME}
	exit_val=$?
	[ "$(cat ${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME})" == "" ] && rm -rf ${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME}
#	while [ "$exit_val" == "" ];do $EYOU_MAIL watch $EYOU_SYS_NAME > /dev/null 2>&1;exit_val=$?;done
	while [ "$exit_val" == "" ];do $EYOU_MAIL watch $EYOU_SYS_NAME 1 > /dev/null 2>>${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME};exit_val=$?;done
	if [ "$exit_val" == "0" ];then
		exit_val=0
	else
		echo '======'>>${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME}
		echo $exit_val >>${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME}
		echo '======'>>${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME}
		echo "$DATE_MESS $(hostname) $EYOU_SYS_NAME status fail message... " >> ${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME}
		$EYOU_MAIL watch $EYOU_SYS_NAME >> ${EYOU_SER_FAIL_FILE_CONF}_${EYOU_SYS_NAME} 2>&1
		exit_val=$?
		if [ "$exit_val" != "0" ];then
			exit_val=1
			echo "$DATE_MESS $(hostname) $EYOU_SYS_NAME status [ 检测失败 ] [ ERROR ]" >>$EYOU_SER_FILE_CONF
			$SENDMAIL_FILE/take_snap $EYOU_SYS_NAME >/dev/null 2>&1
		fi
	fi
}

eyou_stop () {
#	if $EYOU_MAIL stop $EYOU_SYS_NAME >/dev/null 2>&1;then
	$EYOU_MAIL stop $EYOU_SYS_NAME >/dev/null 2>&1
	exit_val=$?
	while [ "$exit_val" == "" ];do $EYOU_MAIL stop $EYOU_SYS_NAME > /dev/null 2>&1;exit_val=$?;done
	if [ "$exit_val" == "0" ];then
#			SYS_PID_NUM=$(tail -1 $EYOU_SYS_PID_FILE)
#			ps -ef |grep _${$EYOU_SYS_NAME} 
			if [ "$EYOU_SYS_NAME" == "mysql" ] || [ "$EYOU_SYS_NAME" == "mysql_index" ] || [ "$EYOU_SYS_NAME" == "mysql_log" ] || [ "$EYOU_SYS_NAME" == "mproxy" ] || [ "$EYOU_SYS_NAME" == "mproxy_index" ] || [ "$EYOU_SYS_NAME" == "memcache_session" ] || [ "$EYOU_SYS_NAME" == "memcache_fix" ] || [ "$EYOU_SYS_NAME" == "memcache_hot" ];then
			:
			else
				if [ "$($EYOU_MAIL watch $EYOU_SYS_NAME |grep \/|awk '{print $1}'|wc -l)" == "0" ];then
					:
				else
					$EYOU_MAIL watch $EYOU_SYS_NAME |grep \/|awk '{print $1}'|xargs kill -9 
				fi
			fi
	echo "$DATE_MESS $(hostname) $EYOU_SYS_NAME stop [ 停止成功 ] [ OK ]" >>$EYOU_SER_FILE_CONF
	[ -f $EYOU_SYS_PID_FILE ] && rm -rf $EYOU_SYS_PID_FILE
	exit_val=0
	else
	echo "$DATE_MESS $(hostname) $EYOU_SYS_NAME stop [ 停止失败 ] [ ERROR ]" >>$EYOU_SER_FILE_CONF
	exit_val=1
	fi

}

case $1 in
	start)
		eyou_start
	;;
	status)
		eyou_status
	;;
	stop)
		eyou_stop
	;;
	*)
		echo "Usage: $0 {start|stop|status}"
		exit_val=1
	;;
esac

exit $exit_val
